### ISSUE TITLE
Cannot read property 'exit' of null

### ISSUE THREAD

**Issue by mcmxc** [telbiyski/phantomer#1]
Your pizza example (as well as my piece of code) throws an error `Cannot read property 'exit' of null`.
Any thoughts about that? thanks

**Comment by mcmxc** [comment]
Ok, the problem was because of phantom wasn't available in my PATH. However, horseman have a `phantomPath` option, where you can put a path of your locally installed phantomJS. Can I do so with phantomer?

**Comment by telbiyski** [comment]
Yes in the latest version (1.0.4) - check the readme
